name: derp_learning
channels:
 - conda-forge
 # - https://pose:foldtree@conda.graylab.jhu.edu
dependencies:
 - python<3.10
 # - pyrosetta
 - numpy
 - scipy
 - rdkit
 - numba
 - yapf
 - xarray
 - pytest
 - tqdm
 - pytest-sugar
 - pytest-xdist
 - pip
 - pip:
   - git+git://github.com/willsheffler/willutil.git@master
#   - git+git://github.com/willsheffler/rpxdock.git@master   
