name: derp_learning
channels:
 - conda-forge
 - https://conda.anaconda.org/t/IuO94WfD-JCG/rosettacommons
 - pytorch
dependencies:
 - python>=3.7
 - pyrosetta=2018.52
 - numpy
 - pytorch-cpu
 - torchvision-cpu
 - scipy
 - numba
 - xarray
 - pytest
 - pytest-faulthandler
 - sphinx_rtd_theme
 - ipython
 - cffi
 - black
 - tqdm
 - pytest-sugar
 - pytest-xdist
 - pip:
   - homog >= 0.1.10
   - xbin >= 0.1.5
